services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /Users/tripham/docker/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /Users/tripham/docker/pgadmin:/var/lib/pgadmin
    ports:
      - "18080:80"
    networks:
      - backend
    restart: always

  license-manager:
    container_name: go-license-manager
    image: go-license-manager:latest
    volumes:
      - ./config.toml:/opt/app/conf/config.toml
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    restart: always

networks:
  backend:
    driver: bridge