[server]
http_port=8888
mode="debug"

[superadmin]
username="admin"
password="admin"

[postgres]
host="127.0.0.1"
port="5432"
username="postgres"
password="123qweA#"
database="licenses"
casbin="rbac_rules"

[tracer]
uri="127.0.0.1:4317"